fix UnboundLocalError
If ceph-ceph_deploy is called with:
  'install node1 --no-adjust-repos --nogpgcheck'
python trace shows this error:
  UnboundLocalError: local variable 'extra_install_flags'
  referenced before assignment

Signed-off-by: Danny Al-Gaaf <danny.al-gaaf@bisect.de>